In [1]:
import numpy as np

In [2]:
np.random.random(3)

array([0.04916838, 0.45242245, 0.09882306])

In [3]:
np.random.randint(-2, 2, (10, 2))

array([[ 1, -1],
       [-2,  0],
       [-2,  1],
       [ 1, -2],
       [-2,  0],
       [-2,  1],
       [ 0, -1],
       [-1, -2],
       [ 0, -2],
       [ 0,  0]])

In [5]:
np.random.uniform(-2, 2, 3)

array([ 1.43744517, -0.38318184,  0.64492919])

In [7]:
np.random.randint(-3, 3)

-3